var invert = require('invert-obj');

function StipulationType (stipulationType) {
  this.message = stipulationType;
}

StipulationType.prototype.value = function () {
  return this.message;
};


StipulationType.Keys = {
  'AMT': 'AMT',
  'AUTO_REINVESTMENT_AT_RATE_OR_BETTER': 'AUTOREINV',
  'BANK_QUALIFIED': 'BANKQUAL',
  'BARGAIN_CONDITIONS_SEE': 'BGNCON',
  'COUPON_RANGE': 'COUPON',
  'ISO_CURRENCY_CODE': 'CURRENCY',
  'CUSTOM_START_END_DATE': 'CUSTOMDATE',
  'GEOGRAPHICS_AND_RANGE': 'GEOG',
  'VALUATION_DISCOUNT': 'HAIRCUT',
  'INSURED': 'INSURED',
  'YEAR_OR_YEAR_MONTH_OF_ISSUE': 'ISSUE',
  'ISSUERS_TICKER': 'ISSUER',
  'ISSUE_SIZE_RANGE': 'ISSUESIZE',
  'LOOKBACK_DAYS': 'LOOKBACK',
  'EXPLICIT_LOT_IDENTIFIER': 'LOT',
  'LOT_VARIANCE': 'LOTVAR',
  'MATURITY_YEAR_AND_MONTH': 'MAT',
  'MATURITY_RANGE': 'MATURITY',
  'MAXIMUM_SUBSTITUTIONS': 'MAXSUBS',
  'MINIMUM_QUANTITY': 'MINQTY',
  'MINIMUM_INCREMENT': 'MININCR',
  'MINIMUM_DENOMINATION': 'MINDNOM',
  'PAYMENT_FREQUENCY_CALENDAR': 'PAYFREQ',
  'NUMBER_OF_PIECES': 'PIECES',
  'POOLS_MAXIMUM': 'PMAX',
  'POOLS_PER_MILLION': 'PPM',
  'POOLS_PER_LOT': 'PPL',
  'POOLS_PER_TRADE': 'PPT',
  'PRICE_RANGE': 'PRICE',
  'PRICING_FREQUENCY': 'PRICEFREQ',
  'PRODUCTION_YEAR': 'PROD',
  'CALL_PROTECTION': 'PROTECT',
  'PURPOSE': 'PURPOSE',
  'BENCHMARK_PRICE_SOURCE': 'PXSOURCE',
  'RATING_SOURCE_AND_RANGE': 'RATING',
  'TYPE_OF_REDEMPTION_VALUES_ARE_NONCALLABLE_CALLABLE_PREFUNDED_ESCROWEDTOMATURITY_PUTABLE_CONVERTIBLE': 'REDEMPTION',
  'RESTRICTED': 'RESTRICTED',
  'MARKET_SECTOR': 'SECTOR',
  'SECURITYTYPE_INCLUDED_OR_EXCLUDED': 'SECTYPE',
  'STRUCTURE': 'STRUCT',
  'SUBSTITUTIONS_FREQUENCY': 'SUBSFREQ',
  'SUBSTITUTIONS_LEFT': 'SUBSLEFT',
  'FREEFORM_TEXT': 'TEXT',
  'TRADE_VARIANCE': 'TRDVAR',
  'WEIGHTED_AVERAGE_COUPONVALUE_IN_PERCENT': 'WAC',
  'WEIGHTED_AVERAGE_LIFE_COUPON_VALUE_IN_PERCENT': 'WAL',
  'WEIGHTED_AVERAGE_LOAN_AGE_VALUE_IN_MONTHS': 'WALA',
  'WEIGHTED_AVERAGE_MATURITY_VALUE_IN_MONTHS': 'WAM',
  'WHOLE_POOL': 'WHOLE',
  'YIELD_RANGE': 'YIELD',
};

StipulationType.Tag = '233';

StipulationType.Type = 'STRING';

StipulationType.Values = invert(StipulationType.Keys);

module.exports = StipulationType;